[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = espidf
lib_deps = https://github.com/blues/note-espidf.git
build_flags = -I.pio/libdeps/esp32-c3-devkitc-02/note-espidf/note-c
    -DCONFIG_NOTECARD_I2C_TIMEOUT_MS=1000 # menu config doesnt run on the notecard library
    -DCONFIG_NOTECARD_UART_TIMEOUT_MS=1000
upload_port = COM12
monitor_port = COM12
upload_speed = 115200
monitor_speed = 115200
